// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BCS.proto

#include "BCS.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

extern PROTOBUF_INTERNAL_EXPORT_BCS_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Chain_Transaction_BCS_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_BCS_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_Chain_Block_BCS_2eproto;
namespace BCS {
class Chain_TransactionDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Chain_Transaction> _instance;
} _Chain_Transaction_default_instance_;
class Chain_BlockDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Chain_Block> _instance;
} _Chain_Block_default_instance_;
class ChainDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Chain> _instance;
} _Chain_default_instance_;
}  // namespace BCS
static void InitDefaultsChain_Transaction_BCS_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::BCS::_Chain_Transaction_default_instance_;
    new (ptr) ::BCS::Chain_Transaction();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::BCS::Chain_Transaction::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Chain_Transaction_BCS_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsChain_Transaction_BCS_2eproto}, {}};

static void InitDefaultsChain_Block_BCS_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::BCS::_Chain_Block_default_instance_;
    new (ptr) ::BCS::Chain_Block();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::BCS::Chain_Block::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_Chain_Block_BCS_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsChain_Block_BCS_2eproto}, {
      &scc_info_Chain_Transaction_BCS_2eproto.base,}};

static void InitDefaultsChain_BCS_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::BCS::_Chain_default_instance_;
    new (ptr) ::BCS::Chain();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::BCS::Chain::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_Chain_BCS_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsChain_BCS_2eproto}, {
      &scc_info_Chain_Block_BCS_2eproto.base,}};

void InitDefaults_BCS_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_Chain_Transaction_BCS_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Chain_Block_BCS_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Chain_BCS_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_BCS_2eproto[3];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_BCS_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_BCS_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_BCS_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::BCS::Chain_Transaction, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::BCS::Chain_Transaction, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::BCS::Chain_Transaction, fromaddress_),
  PROTOBUF_FIELD_OFFSET(::BCS::Chain_Transaction, toaddress_),
  PROTOBUF_FIELD_OFFSET(::BCS::Chain_Transaction, amount_),
  PROTOBUF_FIELD_OFFSET(::BCS::Chain_Transaction, hash_),
  0,
  1,
  3,
  2,
  PROTOBUF_FIELD_OFFSET(::BCS::Chain_Block, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::BCS::Chain_Block, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::BCS::Chain_Block, transactions_),
  PROTOBUF_FIELD_OFFSET(::BCS::Chain_Block, prevhash_),
  PROTOBUF_FIELD_OFFSET(::BCS::Chain_Block, txroot_),
  ~0u,
  0,
  1,
  PROTOBUF_FIELD_OFFSET(::BCS::Chain, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::BCS::Chain, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::BCS::Chain, blocks_),
  ~0u,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 9, sizeof(::BCS::Chain_Transaction)},
  { 13, 21, sizeof(::BCS::Chain_Block)},
  { 24, 30, sizeof(::BCS::Chain)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::BCS::_Chain_Transaction_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::BCS::_Chain_Block_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::BCS::_Chain_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_BCS_2eproto = {
  {}, AddDescriptors_BCS_2eproto, "BCS.proto", schemas,
  file_default_instances, TableStruct_BCS_2eproto::offsets,
  file_level_metadata_BCS_2eproto, 3, file_level_enum_descriptors_BCS_2eproto, file_level_service_descriptors_BCS_2eproto,
};

const char descriptor_table_protodef_BCS_2eproto[] =
  "\n\tBCS.proto\022\003BCS\"\327\001\n\005Chain\022 \n\006blocks\030\001 \003"
  "(\0132\020.BCS.Chain.Block\032S\n\013Transaction\022\023\n\013f"
  "romaddress\030\001 \002(\t\022\021\n\ttoaddress\030\002 \002(\t\022\016\n\006a"
  "mount\030\003 \002(\001\022\014\n\004hash\030\004 \002(\t\032W\n\005Block\022,\n\014tr"
  "ansactions\030\001 \003(\0132\026.BCS.Chain.Transaction"
  "\022\020\n\010prevhash\030\002 \002(\t\022\016\n\006txroot\030\003 \002(\t"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_BCS_2eproto = {
  false, InitDefaults_BCS_2eproto, 
  descriptor_table_protodef_BCS_2eproto,
  "BCS.proto", &assign_descriptors_table_BCS_2eproto, 234,
};

void AddDescriptors_BCS_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_BCS_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_BCS_2eproto = []() { AddDescriptors_BCS_2eproto(); return true; }();
namespace BCS {

// ===================================================================

void Chain_Transaction::InitAsDefaultInstance() {
}
class Chain_Transaction::HasBitSetters {
 public:
  static void set_has_fromaddress(Chain_Transaction* msg) {
    msg->_has_bits_[0] |= 0x00000001u;
  }
  static void set_has_toaddress(Chain_Transaction* msg) {
    msg->_has_bits_[0] |= 0x00000002u;
  }
  static void set_has_amount(Chain_Transaction* msg) {
    msg->_has_bits_[0] |= 0x00000008u;
  }
  static void set_has_hash(Chain_Transaction* msg) {
    msg->_has_bits_[0] |= 0x00000004u;
  }
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Chain_Transaction::kFromaddressFieldNumber;
const int Chain_Transaction::kToaddressFieldNumber;
const int Chain_Transaction::kAmountFieldNumber;
const int Chain_Transaction::kHashFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Chain_Transaction::Chain_Transaction()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:BCS.Chain.Transaction)
}
Chain_Transaction::Chain_Transaction(const Chain_Transaction& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  fromaddress_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_fromaddress()) {
    fromaddress_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.fromaddress_);
  }
  toaddress_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_toaddress()) {
    toaddress_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.toaddress_);
  }
  hash_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_hash()) {
    hash_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.hash_);
  }
  amount_ = from.amount_;
  // @@protoc_insertion_point(copy_constructor:BCS.Chain.Transaction)
}

void Chain_Transaction::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_Chain_Transaction_BCS_2eproto.base);
  fromaddress_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  toaddress_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  hash_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  amount_ = 0;
}

Chain_Transaction::~Chain_Transaction() {
  // @@protoc_insertion_point(destructor:BCS.Chain.Transaction)
  SharedDtor();
}

void Chain_Transaction::SharedDtor() {
  fromaddress_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  toaddress_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  hash_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Chain_Transaction::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Chain_Transaction& Chain_Transaction::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_Chain_Transaction_BCS_2eproto.base);
  return *internal_default_instance();
}


void Chain_Transaction::Clear() {
// @@protoc_insertion_point(message_clear_start:BCS.Chain.Transaction)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      fromaddress_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000002u) {
      toaddress_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000004u) {
      hash_.ClearNonDefaultToEmptyNoArena();
    }
  }
  amount_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* Chain_Transaction::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<Chain_Transaction*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // required string fromaddress = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("BCS.Chain.Transaction.fromaddress");
        object = msg->mutable_fromaddress();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8Verify;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8Verify(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // required string toaddress = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 18) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("BCS.Chain.Transaction.toaddress");
        object = msg->mutable_toaddress();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8Verify;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8Verify(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // required double amount = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 25) goto handle_unusual;
        msg->set_amount(::google::protobuf::io::UnalignedLoad<double>(ptr));
        ptr += sizeof(double);
        break;
      }
      // required string hash = 4;
      case 4: {
        if (static_cast<::google::protobuf::uint8>(tag) != 34) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("BCS.Chain.Transaction.hash");
        object = msg->mutable_hash();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8Verify;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8Verify(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool Chain_Transaction::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:BCS.Chain.Transaction)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string fromaddress = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_fromaddress()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->fromaddress().data(), static_cast<int>(this->fromaddress().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "BCS.Chain.Transaction.fromaddress");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string toaddress = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (18 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_toaddress()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->toaddress().data(), static_cast<int>(this->toaddress().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "BCS.Chain.Transaction.toaddress");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required double amount = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (25 & 0xFF)) {
          HasBitSetters::set_has_amount(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &amount_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string hash = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (34 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_hash()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->hash().data(), static_cast<int>(this->hash().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "BCS.Chain.Transaction.hash");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:BCS.Chain.Transaction)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:BCS.Chain.Transaction)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void Chain_Transaction::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:BCS.Chain.Transaction)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string fromaddress = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->fromaddress().data(), static_cast<int>(this->fromaddress().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "BCS.Chain.Transaction.fromaddress");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->fromaddress(), output);
  }

  // required string toaddress = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->toaddress().data(), static_cast<int>(this->toaddress().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "BCS.Chain.Transaction.toaddress");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->toaddress(), output);
  }

  // required double amount = 3;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->amount(), output);
  }

  // required string hash = 4;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->hash().data(), static_cast<int>(this->hash().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "BCS.Chain.Transaction.hash");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->hash(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:BCS.Chain.Transaction)
}

::google::protobuf::uint8* Chain_Transaction::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:BCS.Chain.Transaction)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string fromaddress = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->fromaddress().data(), static_cast<int>(this->fromaddress().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "BCS.Chain.Transaction.fromaddress");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->fromaddress(), target);
  }

  // required string toaddress = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->toaddress().data(), static_cast<int>(this->toaddress().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "BCS.Chain.Transaction.toaddress");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->toaddress(), target);
  }

  // required double amount = 3;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->amount(), target);
  }

  // required string hash = 4;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->hash().data(), static_cast<int>(this->hash().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "BCS.Chain.Transaction.hash");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->hash(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:BCS.Chain.Transaction)
  return target;
}

size_t Chain_Transaction::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:BCS.Chain.Transaction)
  size_t total_size = 0;

  if (has_fromaddress()) {
    // required string fromaddress = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->fromaddress());
  }

  if (has_toaddress()) {
    // required string toaddress = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->toaddress());
  }

  if (has_hash()) {
    // required string hash = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->hash());
  }

  if (has_amount()) {
    // required double amount = 3;
    total_size += 1 + 8;
  }

  return total_size;
}
size_t Chain_Transaction::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:BCS.Chain.Transaction)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x0000000f) ^ 0x0000000f) == 0) {  // All required fields are present.
    // required string fromaddress = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->fromaddress());

    // required string toaddress = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->toaddress());

    // required string hash = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->hash());

    // required double amount = 3;
    total_size += 1 + 8;

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Chain_Transaction::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:BCS.Chain.Transaction)
  GOOGLE_DCHECK_NE(&from, this);
  const Chain_Transaction* source =
      ::google::protobuf::DynamicCastToGenerated<Chain_Transaction>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:BCS.Chain.Transaction)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:BCS.Chain.Transaction)
    MergeFrom(*source);
  }
}

void Chain_Transaction::MergeFrom(const Chain_Transaction& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:BCS.Chain.Transaction)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _has_bits_[0] |= 0x00000001u;
      fromaddress_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.fromaddress_);
    }
    if (cached_has_bits & 0x00000002u) {
      _has_bits_[0] |= 0x00000002u;
      toaddress_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.toaddress_);
    }
    if (cached_has_bits & 0x00000004u) {
      _has_bits_[0] |= 0x00000004u;
      hash_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.hash_);
    }
    if (cached_has_bits & 0x00000008u) {
      amount_ = from.amount_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void Chain_Transaction::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:BCS.Chain.Transaction)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Chain_Transaction::CopyFrom(const Chain_Transaction& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:BCS.Chain.Transaction)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Chain_Transaction::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;
  return true;
}

void Chain_Transaction::Swap(Chain_Transaction* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Chain_Transaction::InternalSwap(Chain_Transaction* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  fromaddress_.Swap(&other->fromaddress_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  toaddress_.Swap(&other->toaddress_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  hash_.Swap(&other->hash_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(amount_, other->amount_);
}

::google::protobuf::Metadata Chain_Transaction::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_BCS_2eproto);
  return ::file_level_metadata_BCS_2eproto[kIndexInFileMessages];
}


// ===================================================================

void Chain_Block::InitAsDefaultInstance() {
}
class Chain_Block::HasBitSetters {
 public:
  static void set_has_prevhash(Chain_Block* msg) {
    msg->_has_bits_[0] |= 0x00000001u;
  }
  static void set_has_txroot(Chain_Block* msg) {
    msg->_has_bits_[0] |= 0x00000002u;
  }
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Chain_Block::kTransactionsFieldNumber;
const int Chain_Block::kPrevhashFieldNumber;
const int Chain_Block::kTxrootFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Chain_Block::Chain_Block()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:BCS.Chain.Block)
}
Chain_Block::Chain_Block(const Chain_Block& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_),
      transactions_(from.transactions_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  prevhash_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_prevhash()) {
    prevhash_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.prevhash_);
  }
  txroot_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_txroot()) {
    txroot_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.txroot_);
  }
  // @@protoc_insertion_point(copy_constructor:BCS.Chain.Block)
}

void Chain_Block::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_Chain_Block_BCS_2eproto.base);
  prevhash_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  txroot_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

Chain_Block::~Chain_Block() {
  // @@protoc_insertion_point(destructor:BCS.Chain.Block)
  SharedDtor();
}

void Chain_Block::SharedDtor() {
  prevhash_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  txroot_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Chain_Block::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Chain_Block& Chain_Block::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_Chain_Block_BCS_2eproto.base);
  return *internal_default_instance();
}


void Chain_Block::Clear() {
// @@protoc_insertion_point(message_clear_start:BCS.Chain.Block)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  transactions_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      prevhash_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000002u) {
      txroot_.ClearNonDefaultToEmptyNoArena();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* Chain_Block::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<Chain_Block*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // repeated .BCS.Chain.Transaction transactions = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        do {
          ptr = ::google::protobuf::io::ReadSize(ptr, &size);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          parser_till_end = ::BCS::Chain_Transaction::_InternalParse;
          object = msg->add_transactions();
          if (size > end - ptr) goto len_delim_till_end;
          ptr += size;
          GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
              {parser_till_end, object}, ptr - size, ptr));
          if (ptr >= end) break;
        } while ((::google::protobuf::io::UnalignedLoad<::google::protobuf::uint64>(ptr) & 255) == 10 && (ptr += 1));
        break;
      }
      // required string prevhash = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 18) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("BCS.Chain.Block.prevhash");
        object = msg->mutable_prevhash();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8Verify;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8Verify(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // required string txroot = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 26) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("BCS.Chain.Block.txroot");
        object = msg->mutable_txroot();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8Verify;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8Verify(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool Chain_Block::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:BCS.Chain.Block)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .BCS.Chain.Transaction transactions = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_transactions()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string prevhash = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (18 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_prevhash()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->prevhash().data(), static_cast<int>(this->prevhash().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "BCS.Chain.Block.prevhash");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string txroot = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (26 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_txroot()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->txroot().data(), static_cast<int>(this->txroot().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "BCS.Chain.Block.txroot");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:BCS.Chain.Block)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:BCS.Chain.Block)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void Chain_Block::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:BCS.Chain.Block)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .BCS.Chain.Transaction transactions = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->transactions_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->transactions(static_cast<int>(i)),
      output);
  }

  cached_has_bits = _has_bits_[0];
  // required string prevhash = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->prevhash().data(), static_cast<int>(this->prevhash().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "BCS.Chain.Block.prevhash");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->prevhash(), output);
  }

  // required string txroot = 3;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->txroot().data(), static_cast<int>(this->txroot().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "BCS.Chain.Block.txroot");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->txroot(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:BCS.Chain.Block)
}

::google::protobuf::uint8* Chain_Block::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:BCS.Chain.Block)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .BCS.Chain.Transaction transactions = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->transactions_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->transactions(static_cast<int>(i)), target);
  }

  cached_has_bits = _has_bits_[0];
  // required string prevhash = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->prevhash().data(), static_cast<int>(this->prevhash().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "BCS.Chain.Block.prevhash");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->prevhash(), target);
  }

  // required string txroot = 3;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->txroot().data(), static_cast<int>(this->txroot().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "BCS.Chain.Block.txroot");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->txroot(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:BCS.Chain.Block)
  return target;
}

size_t Chain_Block::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:BCS.Chain.Block)
  size_t total_size = 0;

  if (has_prevhash()) {
    // required string prevhash = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->prevhash());
  }

  if (has_txroot()) {
    // required string txroot = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->txroot());
  }

  return total_size;
}
size_t Chain_Block::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:BCS.Chain.Block)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required string prevhash = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->prevhash());

    // required string txroot = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->txroot());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .BCS.Chain.Transaction transactions = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->transactions_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->transactions(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Chain_Block::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:BCS.Chain.Block)
  GOOGLE_DCHECK_NE(&from, this);
  const Chain_Block* source =
      ::google::protobuf::DynamicCastToGenerated<Chain_Block>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:BCS.Chain.Block)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:BCS.Chain.Block)
    MergeFrom(*source);
  }
}

void Chain_Block::MergeFrom(const Chain_Block& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:BCS.Chain.Block)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  transactions_.MergeFrom(from.transactions_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _has_bits_[0] |= 0x00000001u;
      prevhash_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.prevhash_);
    }
    if (cached_has_bits & 0x00000002u) {
      _has_bits_[0] |= 0x00000002u;
      txroot_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.txroot_);
    }
  }
}

void Chain_Block::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:BCS.Chain.Block)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Chain_Block::CopyFrom(const Chain_Block& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:BCS.Chain.Block)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Chain_Block::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->transactions())) return false;
  return true;
}

void Chain_Block::Swap(Chain_Block* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Chain_Block::InternalSwap(Chain_Block* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  CastToBase(&transactions_)->InternalSwap(CastToBase(&other->transactions_));
  prevhash_.Swap(&other->prevhash_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  txroot_.Swap(&other->txroot_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::google::protobuf::Metadata Chain_Block::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_BCS_2eproto);
  return ::file_level_metadata_BCS_2eproto[kIndexInFileMessages];
}


// ===================================================================

void Chain::InitAsDefaultInstance() {
}
class Chain::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Chain::kBlocksFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Chain::Chain()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:BCS.Chain)
}
Chain::Chain(const Chain& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_),
      blocks_(from.blocks_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:BCS.Chain)
}

void Chain::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_Chain_BCS_2eproto.base);
}

Chain::~Chain() {
  // @@protoc_insertion_point(destructor:BCS.Chain)
  SharedDtor();
}

void Chain::SharedDtor() {
}

void Chain::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Chain& Chain::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_Chain_BCS_2eproto.base);
  return *internal_default_instance();
}


void Chain::Clear() {
// @@protoc_insertion_point(message_clear_start:BCS.Chain)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  blocks_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* Chain::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<Chain*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // repeated .BCS.Chain.Block blocks = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        do {
          ptr = ::google::protobuf::io::ReadSize(ptr, &size);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          parser_till_end = ::BCS::Chain_Block::_InternalParse;
          object = msg->add_blocks();
          if (size > end - ptr) goto len_delim_till_end;
          ptr += size;
          GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
              {parser_till_end, object}, ptr - size, ptr));
          if (ptr >= end) break;
        } while ((::google::protobuf::io::UnalignedLoad<::google::protobuf::uint64>(ptr) & 255) == 10 && (ptr += 1));
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool Chain::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:BCS.Chain)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .BCS.Chain.Block blocks = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_blocks()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:BCS.Chain)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:BCS.Chain)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void Chain::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:BCS.Chain)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .BCS.Chain.Block blocks = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->blocks_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->blocks(static_cast<int>(i)),
      output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:BCS.Chain)
}

::google::protobuf::uint8* Chain::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:BCS.Chain)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .BCS.Chain.Block blocks = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->blocks_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->blocks(static_cast<int>(i)), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:BCS.Chain)
  return target;
}

size_t Chain::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:BCS.Chain)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .BCS.Chain.Block blocks = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->blocks_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->blocks(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Chain::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:BCS.Chain)
  GOOGLE_DCHECK_NE(&from, this);
  const Chain* source =
      ::google::protobuf::DynamicCastToGenerated<Chain>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:BCS.Chain)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:BCS.Chain)
    MergeFrom(*source);
  }
}

void Chain::MergeFrom(const Chain& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:BCS.Chain)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  blocks_.MergeFrom(from.blocks_);
}

void Chain::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:BCS.Chain)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Chain::CopyFrom(const Chain& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:BCS.Chain)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Chain::IsInitialized() const {
  if (!::google::protobuf::internal::AllAreInitialized(this->blocks())) return false;
  return true;
}

void Chain::Swap(Chain* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Chain::InternalSwap(Chain* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  CastToBase(&blocks_)->InternalSwap(CastToBase(&other->blocks_));
}

::google::protobuf::Metadata Chain::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_BCS_2eproto);
  return ::file_level_metadata_BCS_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace BCS
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::BCS::Chain_Transaction* Arena::CreateMaybeMessage< ::BCS::Chain_Transaction >(Arena* arena) {
  return Arena::CreateInternal< ::BCS::Chain_Transaction >(arena);
}
template<> PROTOBUF_NOINLINE ::BCS::Chain_Block* Arena::CreateMaybeMessage< ::BCS::Chain_Block >(Arena* arena) {
  return Arena::CreateInternal< ::BCS::Chain_Block >(arena);
}
template<> PROTOBUF_NOINLINE ::BCS::Chain* Arena::CreateMaybeMessage< ::BCS::Chain >(Arena* arena) {
  return Arena::CreateInternal< ::BCS::Chain >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
